### ISSUE TITLE
Switching workspaces is broken

### ISSUE THREAD

**Issue by EmmanuelMess** [mzur/gnome-shell-wsmatrix#65] opened 2019-10-10 20:39 UTC
Ubuntu 18.04
Gnome 3.30.1

After updating gnome version and restarting switching workspaces and moving windows doesn't work.

```<ctrl><alt><left>```, ```<ctrl><alt><right>``` only show the working environments but doesn't move, fixed by: uninstaling the extension, restarting and opening Gnome with Xorg, Alt+F2 <r>'ing, going to settings and manually setting the shortcuts.

```<ctrl><shift><alt><left>```, ```<ctrl><shift><alt><right>``` works after uninstalling the extension, restarting and opening Gnome with Xorg and Alt+F2 <r>'ing. 

Moving window left breaks after a while.

**Comment by mzur** [comment] 2019-10-12 10:02
Can anybody reproduce this? Maybe GNOME 3.30 does not work correctly on Ubuntu 18.04. The official package for this Ubuntu version is GNOME 3.28.

**Comment by EmmanuelMess** [comment] 2019-10-14 18:23
Doing this in gconfig seems to work, I do still have to test if it will reset after a while.

![Captura de pantalla de 2019-10-14 15-21-53](https://user-images.githubusercontent.com/10991116/66773873-752e8980-ee96-11e9-91b3-0e2c45825520.png)

**Comment by lautarodragan** [comment] 2019-10-18 17:13
Did a clean install of Pop_OS! 19.04 (which is basically an Ubuntu 19.04 AFAIK) and this plugin yesterday and it's working fine for me. Running gnome 3.32.2.

**Comment by felubra** [comment] 2019-10-19 16:51
Just installed the extension in gnome 3.32.2 (Fedora 30) and it's working fine.

**Comment by EmmanuelMess** [comment] 2019-10-20 00:32
Should I update to 3.32.2?

**Comment by ebeem** [comment] 2019-10-22 19:49
if you can test on a clean version of the distro you use, it will be so helpful.
Also, if you can let us know what environment we can test on to reproduce, we will be able to debug better.

This doesn't seem like a bug with the extension to me.

**Comment by ebeem** [comment] 2019-11-01 09:03
@EmmanuelMess Can you please confirm whether you are still facing this issue or not?
I think if this issue occurs because of `WSMatrix`, then it needs more attention.

Please let us know whether you are still facing this issue or not, and what environment can we use to reproduce it. That way we can debug and fix the problem.

**Comment by EmmanuelMess** [comment] 2019-11-03 17:09
> Please let us know whether you are still facing this issue or not, and what environment can we use to reproduce it. That way we can debug and fix the problem.

No, after reconfiguring with dconf as said [here](https://github.com/mzur/gnome-shell-wsmatrix/issues/65#issuecomment-541839841) , the issue was fixed.

**Comment by ebeem** [comment] 2019-11-03 17:26
thanks, I am closing this for now, if you think what happened to you is reproducable then let us know so we reopen this issue and try to fix it.

**Closed by ebeem** 2019-11-03 17:26 UTC
Labels: needs info
