### ISSUE TITLE
Show-workspace-thumbnails is slow

### ISSUE THREAD

**Issue by JBakamovic** [mzur/gnome-shell-wsmatrix#31] opened 2019-05-14 08:03 UTC
Nice extension! But when `show-workspace-thumbnails` option is enabled, quite noticeable delay is visible while switching between workspaces. Turning it off makes this problem disappear.

**Comment by ebeem** [comment] 2019-05-14 12:43
there is an option now to **Cache popup**
it has been merged into master recently, please try to clone the master and try it out
Note: this feature is disabled by default, you need to enable it from preferences

![Screenshot from 2019-05-14 15-41-12](https://user-images.githubusercontent.com/25146039/57698723-ee634f80-765e-11e9-8cc5-eec819ecfcd3.png)

let us know if this helps

**Comment by JBakamovic** [comment] 2019-05-14 14:59
Unfortunately still quite slow. Seems like rendering those thumbnails are killing the performance (i5-8350U with 32GB RAM). I haven't experienced such slow downs with (original) workspace-grid extension though. For now, I will be disabling thumbnails completely. Then it's blazing fast.

Thanks for quick feedback!

**Comment by ebeem** [comment] 2019-05-14 16:38
enabling the feature above will cache the switcher, it will not rerender it again.
the performance should be almost similar when enabling and disabling thumbnails as long as you enable the option `Cache popup (faster, consumes more memory)`
are you sure this option appears in your preferences and you have enabled it

if so, then it will probably be very hard to optimize it more.

**Comment by JBakamovic** [comment] 2019-05-15 07:55
> enabling the feature above will cache the switcher, it will not rerender from scratch again.

**Comment by mzur** [comment] 2019-05-15 08:55
I agree with @ebeem, enabling the caching should substantially improve the performance if you have noticeable lags. How many workspaces do you use? Maybe there is an issue that prevents the caching from being enabled.

> I am not a JS expert but other extension did it somehow.

I am not aware of Workspace Grid supporting workspace thumbnails. That was the reason why I created Workspace Matrix in the first place. Can you please explain what you mean?

**Comment by JBakamovic** [comment] 2019-05-15 09:00
It did improve and it is running but it is still slow and stutters the transitions between workspaces. I am using 9 workspaces.

> Can you please explain what you mean?

It indeed does not have that feature. Hmmm, sorry for confusion.

**Comment by mzur** [comment] 2019-05-15 09:02
Which Linux distro and version, and which GNOME version do you use? Do you use Wayland?

**Comment by JBakamovic** [comment] 2019-05-15 09:17
Fedora 31 with Wayland desktop.

```
gnome-shell --version
GNOME Shell 3.32.1
```

**Comment by mzur** [comment] 2019-05-15 09:55
Does the performance improve if you switch to Xorg?

**Comment by JBakamovic** [comment] 2019-05-15 10:47
Noup.

**Comment by mzur** [comment] 2019-05-15 11:08
Do you have a monitor with a very high resolution (e.g. 4k)?

**Comment by ebeem** [comment] 2019-05-15 13:04
`GNOME` itself is a little bit laggy. It has improved a lot in performance since `3.32`, but it's still far from perfect. Animations in `GNOME` are slow compared to other Desktop Environments like `KDE`.

extensions do make `GNOME` perform worse, but I think this extension with caching is in a stage where it's very hard to optimize it more.

I tested the extension on my virtual machine with 1 CPU core only, and it performed well, but after having a lot of windows open, it started slowing down while showing the transition animation between workspaces. Disabling the extension makes it a bit faster, but I think this is an issue with `mutter` rather than the extension.

if the problem is with the extension, then `GNOME` should freeze before showing the popup switcher and then start the transition animation. In my case, the popup switcher appear but the transition is laggy.

**Comment by JBakamovic** [comment] 2019-05-16 08:10
> Do you have a monitor with a very high resolution (e.g. 4k)?

Not very high but 2k.

> but after having a lot of windows open, it started slowing down while showing the transition animation between workspaces. 

Exactly. But at my place it happens with 1 or 2 windows per workspace.

> Disabling the extension makes it a bit faster, but I think this is an issue with mutter rather than the extension.

Actually, disabling the thumbnail-preview in extension makes transitions blazingly fast so I would still put my bet on JS rendering performance. Anyhow, performance needs to be measured and not only guessed :)

I forgot to mention that I've got a dual-monitor setup: monitor (2k) connected to laptop (FHD). So, from what it seems it looks like dual-monitor + 2k resolution might be the culprit of the slowdown.

**Comment by ebeem** [comment] 2019-05-16 08:26
you can check this PR for performance measurement #24 
however, this PR only measures the time taken to render the switcher and thumbnails.

if there's something else that we aren't aware of, and it consumes much processing power or time, then let us know about it. It will be so helpful if you can check the time taken to render the switcher and thumbnails and report them here.

according to the tests we made, `0-1 ms` is the time taken to render the switcher and thumbnails with caching enabled.

**Comment by JBakamovic** [comment] 2019-05-16 09:54
Interesting. Currently I am too busy but I will try to take a look at profiling numbers these days and perhaps report what I get on my machine :)

Thanks for the work!

**Comment by scottkosty** [comment] 2019-05-20 19:17
Just to add my own observations. I've found the speed to be satisfactory with the cache enabled. Thanks to all for your work on this!

There is one issue that I'm guessing is known: I think the cache is correctly regenerated when a new window is created on a workspace, but the regeneration does not seem to be regenerated when the ordering of the windows changes (e.g., I use alt-tab to bring a window to the foreground).

**Comment by ebeem** [comment] 2019-05-20 19:27
@scottkosty actually, I've just noticed this one.
I will try to allocate some time to investigate it more. Thanks for your feedback

**Comment by scottkosty** [comment] 2019-05-20 20:17
> actually, I've just noticed this one.

Let me know if you want me to open a separate issue, to keep this one clean.

> I will try to allocate some time to investigate it more. Thanks for your feedback

Awesome, thanks!

**Comment by ebeem** [comment] 2019-05-20 20:22
@JBakamovic yes, since this is a separate issue, I will appreciate it if you can open a new issue

**Comment by ebeem** [comment] 2019-05-21 18:48
@JBakamovic 
I did some investigation, this seems to be a GNOME issue and not related to caching.
steps to reproduce:
```
1- set timeout of workspace popup to 5000ms so you can easily notice the bug.
2- open a small window on the workspace (like nautilus)
3- open a video on the same workspace (like VLC)
4- show the workspace switcher (you can go to another workspace and back to your video workspace)
at this stage, you will notice that the video is playing well in the workspace thumbnail
5- alt-tab to switch application to your application in step#2 and show workspace switcher again
at this stage, you will notice the window hasn't been rendered in the thumbnail, but the video is still being animated
6- move the window at step#2 to another workspace or monitor, then bring it back to the original workspace or monitor
at this stage, you will notice that the window at step#2 has been rendered above the window at step#3 which is the expected behavior.
```

it seems like the GNOME team didn't handle all cases well in thumbnail preview.
in file `workspaceThumbnail.js`


```Javascript
        this._windows = [];
        this._allWindows = [];
        this._minimizedChangedIds = [];
        for (let i = 0; i < windows.length; i++) {
            let minimizedChangedId =
                windows[i].meta_window.connect('notify::minimized',
                                               this._updateMinimized.bind(this));
            this._allWindows.push(windows[i].meta_window);
            this._minimizedChangedIds.push(minimizedChangedId);

            if (this._isMyWindow(windows[i]) && this._isOverviewWindow(windows[i])) {
                this._addWindowClone(windows[i]);
            }
        }

        // Track window changes
        this._windowAddedId = this.metaWorkspace.connect('window-added',
                                                          this._windowAdded.bind(this));
        this._windowRemovedId = this.metaWorkspace.connect('window-removed',
                                                           this._windowRemoved.bind(this));
        this._windowEnteredMonitorId = global.display.connect('window-entered-monitor',
                                                              this._windowEnteredMonitor.bind(this));
        this._windowLeftMonitorId = global.display.connect('window-left-monitor',
                                                           this._windowLeftMonitor.bind(this));
```

looks like the thumbnail handles most changes in windows including minimize/add/remove window and left/entered monitors, but there's no window focus listener, which makes the thumbnail not getting updated if a window has been focused/unfocused.

I think we can make a workaround for this in the extension, but this is probably a GNOME bug and should be fixed by the GNOME team.

**Comment by scottkosty** [comment] 2019-05-21 19:55
> yes, since this is a separate issue, I will appreciate it if you can open a new issue

Done at #33, thanks for looking into it!

**Comment by mzur** [comment] 2019-07-27 09:35
Please reopen if this is still relevant.

**Closed by mzur** 2019-07-27 09:35 UTC
Labels: needs info
