### ISSUE TITLE
Can't Drag/Drop between rows in Ubuntu Show All Applications Window

### ISSUE THREAD

**Issue by gitsnow** [mzur/gnome-shell-wsmatrix#234] opened 2022-07-26 05:21 UTC
Hi,

I'm using Ubuntu 22.04 and when I use the hotkey to "Show All Applications", my 4x2 grid shows up at the top of the screen, but I'm unable to drag windows from the top row to the bottom row and vice-versa.  Also, if I try to drag windows horizontally in the same row, they always jump to the top row no matter what.  Wondering if this is just me or if this is a bug.

Thanks for your time

**Comment by mzur** [comment] 2022-08-08 14:59
This is probably a duplicate of #177. Please reopen if you don't think so.

**Closed by mzur** 2022-08-08 14:59 UTC
