### ISSUE TITLE
Native gestures in Wayland are not compatible

### ISSUE THREAD

**Issue by usersaurus** [mzur/gnome-shell-wsmatrix#43] opened 2019-08-06 18:01 UTC
Looks like Wayland native gestures are buggy if you use this extension. A horizontal 4-fingers swipe results in a incomplete transition and bouncing again to the current workspace. After uninstalling the extension the gesture works correctly (but down to up and vice versa, of course)

O.S. - Ubuntu 19.04

How to reproduce
- Start a Wayland session
- 4-fingers swipe from right to left

**Comment by mzur** [comment] 2019-08-07 16:56
Sorry but I don't have a machine to test this with. Anyone who wants to look into this is welcome. This might even be an upstream issue.

**Comment by jtagcat** [comment] 2019-08-19 15:34
Dupe of #40

**Comment by jtagcat** [comment] 2019-08-19 15:47
There are 2 major problems:
 - With touch you can move freely between the workspaces - even diagonally. It's a headache when trying to do gestures. Without the extension, swiping 30° up still results in a straight line up, as humans are are perfect with their angles. There should not be any diagonal movement, just based on 45° switch points straight right/left up/down switching.
 - You need to perform the gesture on the whole screen - a simple swipe (say total movement with 4 fingers is 5cm) worked without the extension; with the extension, when swiping, you need to swipe the whole screen, resulting you needing to slide painfully 40cm from one side to the other. If you don't do that, when it seems like you are switching, it just goes back.
See [this screencast]() for both issues. Was swiping 30cm.

**Comment by ettavolt** [comment] 2019-09-17 07:26
This happens even when swiping on touchpad (if you manage to put four fingers on it and the touchpad is capable. Mine is capable, maybe because of modprobe's ``options psmouse synaptics_intertouch=1``, [marketing about InterTouch suggests this too](https://investor.synaptics.com/news-releases/news-release-details/synaptics-announces-groundbreaking-intertouch-touchpadtm).

**Comment by MasonMcV** [comment] 2020-08-26 06:18
I am running this on Gnome Shell 3.36.4 and it works perfectly with wayland gestures both on touch screen and trackpad.  

One thing to note though is that it only changes between horizontal workspaces.  

It seems that this bug has been fixed upstream as of August 2020

**Comment by mzur** [comment] 2020-08-29 16:59
Thanks for the info @MasonMcV. Would you say this issue is resolved then?

**Comment by MasonMcV** [comment] 2020-08-30 23:02
@mzur My experience has been that it has been fixed.  
I haven't done any testing on any other systems so I can't be 100% sure.  

I think the issue could probably be marked resolved and then re-opened if anyone has issues in the future.

**Comment by mzur** [comment] 2020-08-31 04:58
Thanks!

**Closed by mzur** 2020-08-31 04:58 UTC
Labels: help wanted, needs info
