### ISSUE TITLE
FC33/Gnome 3.38: No DnD on activity overview

### ISSUE THREAD

**Issue by arjenpdevries** [mzur/gnome-shell-wsmatrix#143] opened 2021-01-20 09:31 UTC
After switching to FC33 and upgrading the extension, it seems that DnD for windows from one workspace to another doesn't work anymore (it used to for FC32 and below).

_Great extension btw!_

**Comment by mzur** [comment] 2021-01-20 12:02
Please have a look at #125, could this be related to some of the unresolved tasks? If not, this should be added as another task. You are very welcome to contribute to the pull request to establish full GNOME 3.38 support.

**Comment by mzur** [comment] 2021-01-20 12:06
I did a quick test with GNOME 3.38 on Arch and DnD works fine there. Do you have any other extensions installed? If so, please disable all of them except this one and try again. Also have a look if there are any errors in `journalctl /usr/bin/gnome-shell`.

**Comment by arjenpdevries** [comment] 2021-01-20 13:17
Thanks for such a quick response!

I disabled all other extensions but that did not help.
The `journalctl` logs do not shed light either, so I guess we have to await other reports to confirm (and I will let you know if the problem disappears).

**Comment by ZeChArtiahSaher** [comment] 2021-02-01 20:59
Can confirm DnD not working fully working for me either. I'm able to DnD windows between workspace previews, but not window tiles to the workspace previews like it used to function before.

**Comment by arjenpdevries** [comment] 2021-02-01 21:06
Thanks @ZeChArtiahSaher I never knew you could do that - at least a temporary workaround!

So the bottom line is:
* DnD works between workspace previews
* DnD does not work if you drag a window from the workspace to a workspace preview

The latter used to work (and I use it a lot for firefox windows :-)).
Glad that it is not something weird in my setup.

**Comment by ZeChArtiahSaher** [comment] 2021-02-02 12:27
I managed to quickly fix functionality by changing: https://github.com/mzur/gnome-shell-wsmatrix/blob/16609ff92e8c512e570fa3ed528357912a911546/wsmatrix%40martin.zurowietz.de/ThumbnailsBoxOverride.js#L292

to 

`if ((!source.realWindow && !source.metaWindow) &&`

But it introduces render bugs on multi-monitor setup if I drag a window out of the preview to the activity. So I'm sure this is breaking and not used as intended.

**Comment by mzur** [comment] 2021-02-03 11:39
Could you please elaborate what you mean with "if you drag a window from the workspace to a workspace preview". For me this works in the activity overview:
- DnD of a window from one workspace thumbnail to another
- DnD of a window at the center of the activity overview (a window from the current workspace) to a workspace thumbnail

**Comment by arjenpdevries** [comment] 2021-02-03 11:46
Interesting, the first works for me but the second does not.

I hope we use the same terminology... 

After pressing Super I can move window thumbnails around in the right-hand panel of workspace previews, but I cannot drag a window from the left-hand side (current workspace representation) to the previews on the right. This used to work before upgrading to FC33. It's not related to Wayland vs. X11.

(Adding a screenshot doesn't work unfortunately)

**Comment by mzur** [comment] 2021-02-03 15:08
I think we are talking about the same things. This definitely works on my Arch VM that I use to test this extension with GNOME 3.38. Do you maybe have other extensions installed that might interfere here? Which version of this extension do you use?

**Comment by arjenpdevries** [comment] 2021-02-03 15:45
I have checked disabling all other extensions and that does not have an effect.

I have version 24 of the extension.

**Comment by mzur** [comment] 2021-02-03 20:37
I just started a stock-Fedora 33 live session and only installed this extension. Both kinds of DnD work for me. You mean Fedora when you say FC33, right?

**Comment by arjenpdevries** [comment] 2021-02-03 21:01
Yes, I do. Very puzzling - thanks for trying it out, even if I cannot explain why it would work for you and not for me. Will try more later.

**Comment by gowza** [comment] 2021-03-09 01:11
I am having the same problem with `DnD of a window at the center of the activity overview (a window from the current workspace) to a workspace thumbnail`.

I agreed with what @ZeChArtiahSaher mentioned that the `source.realWindow` check is giving incorrect result. Looking closer at the checking code, it seems that we got this from the `gnome-shell`'s `workspaceThumbnail.js` file. The current version of that file has moved from checking `realWindow` to checking `metaWindow`.

https://github.com/GNOME/gnome-shell/blob/7a57528bd7940e68c404d15d398f88730821cec9/js/ui/workspaceThumbnail.js#L886-L890

Checking the commit history, the change was done in June last year (https://github.com/GNOME/gnome-shell/commit/46600740fedd6da7344d4693fb8b0721ef063d0c). I am not sure what is the different between `realWindow` and `metaWindow`. However, to keep consistency with the upstream `gnome-shell`, should we move to using `metaWindow`? I did some basic debuggings and it seem that `source.realWindow` is always `undefined`.

**Comment by mzur** [comment] 2021-03-09 06:24
@gowza Can you please check if the problem is resolved if you use `metaWindow` instead of `realWindow`?

**Comment by gowza** [comment] 2021-03-09 08:21
@mzur Yes, can confirm that problem is resolved when I use `metaWindow` instead of `realWindow`.

**Comment by mzur** [comment] 2021-03-09 20:39
Thanks! Can you please send a pull request with the fix?

**Comment by mzur** [comment] 2021-03-10 20:30
A fix has been implemented in #147 and a new version submitted to extensions.gnome.org.

**Closed by mzur** 2021-03-10 20:30 UTC
