### ISSUE TITLE
fails with Gnome 42: TypeError: class heritage GWorkspaceAnimation.MonitorGroup is not an object or null

### ISSUE THREAD

**Issue by drew-parsons** [mzur/gnome-shell-wsmatrix#215] opened 2022-03-27 14:16 UTC
wsmatrix is no longer working with Gnome 42.  42 is not yet listed in shell-version in `.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/metadata.json`, but simply adding it manually is not sufficient to work around the problem.

The error message recorded in logs is
```
Mar 27 16:05:57 sandy gnome-shell[2045]: JS ERROR: Extension wsmatrix@martin.zurowietz.de: TypeError: class heritage GWorkspaceAnimation.MonitorGroup is not an object or null#012@/home/user/.local/share/gnome-sh
ell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceAnimation.js:9:1#012@/home/user/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceManagerOverride.js:2:2
8#012@/home/user/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:3:34#012_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:420:13#012loadExtension@resource:///org
/gnome/shell/ui/extensionSystem.js:345:27#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:594:18#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28#012_loadExtensio
ns@resource:///org/gnome/shell/ui/extensionSystem.js:573:19#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:603:18#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:6
34:18#012init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14#012_initializeUI@resource:///org/gnome/shell/ui/main.js:265:22#012start@resource:///org/gnome/shell/ui/main.js:162:5#012@resource:///org/gnom
e/shell/ui/init.js:6:17
```

**Comment by mzur** [comment] 2022-03-28 06:53
Thanks for reporting. This is a duplicate of #212.

**Closed by mzur** 2022-03-28 06:53 UTC
