### ISSUE TITLE
Windows change workspaces after suspend

### ISSUE THREAD

**Issue by HadiModarres** [mzur/gnome-shell-wsmatrix#29] opened 2019-05-09 05:22 UTC
This extension is very nice, but there is a problem that makes it unusable for me. After waking up from suspend window positions change. 

To reproduce: create a 3x3 matrix and open a terminal in bottom right corner, suspend then terminal position is changed.

**Comment by ebeem** [comment] 2019-05-09 12:25
can you explain what position changes?
do you mean the window moves to another workspace?
or the window moves to another monitor?
or just position on the screen?

**Comment by HadiModarres** [comment] 2019-05-09 13:31
Hi @ebeem 
yes the window moves to another workspace, I tried it many times and thats the case, haven't tried with different monitors

**Comment by HadiModarres** [comment] 2019-05-09 13:39
I'd be happy to help, should I follow this one to get to know gnome shell extensions? https://wiki.gnome.org/Projects/GnomeShell/Extensions/StepByStepTutorial
are there other more concise guides somewhere?

**Comment by ebeem** [comment] 2019-05-09 15:17
I will need to debug this, as far as I am concerned, it didn't happen to me before. I use 3x3 grid.
I will try this and let you know

**Comment by HadiModarres** [comment] 2019-05-09 21:50
Cool :)

**Comment by mzur** [comment] 2019-05-10 09:17
@HadiModarres Do you use a laptop with an external monitor? There might be a delay in setting up the external monitor which pushes the windows back to the workspaces of the internal monitor. I believe this issue is not caused by Workspace Matrix because it has nothing to do with window positioning. It might only increase the visibility of this issue with the 2D grid and static number of workspaces.

**Comment by HadiModarres** [comment] 2019-05-11 03:13
Hi @mzur 
Yes I have my laptop connected to a single external monitor. I tested many times, and what you said is in fact true. The problem isnt there when I only work with laptop screen. Thats unfortunate, because it would be so good for me to dedicate each row to one my tasks, it just fits my workflow so well. So theres nothing that can be done? I'd be happy to help if you point me in the right direction

**Comment by HadiModarres** [comment] 2019-05-11 03:19
@mzur just to be clear, external monitor doesnt cause an issue on its own. I can work with it with no problems and detach and attach the hdmi cable many times. The issue happens only when I suspend the laptop and wake it up again.

**Comment by HadiModarres** [comment] 2019-05-11 03:31
actually, I can't reproduce it anymore, it works well with laptop or external monitor. It may have been caused by a conflict with another extension. I'll close this now, Ill open it again if I find it. 

Thanks @mzur @ebeem

**Comment by s3than** [comment] 2019-05-20 06:43
I don't use an external monitor and can replicate this issue
When I lock screen, whatever was in focus will be moved to the bottom left corner of a 2x2 workspace matrix

**Comment by HadiModarres** [comment] 2019-05-20 07:18
you're right, I'm seeing this behaviour too
there is something wrong with handling of empty of workspaces after attaching to external monitor or locking/suspending

**Comment by mzur** [comment] 2019-05-21 18:25
I still can't reproduce this with Ubuntu 18.04 and GNOME 3.28.3 or Ubuntu 19.04 and GNOME 3.32.0. Which Linux distro and GNOME version do you have?

**Comment by ebeem** [comment] 2019-05-21 18:59
@s3than  
what about restarting gnome (`alt+f2` and type `r`)? does it move the windows?
do you use other extensions that can affect this?

I use the [Auto Move Windows](https://extensions.gnome.org/extension/16/auto-move-windows/) extension which allows me to set a default workspace for each application, if I set firefox default workspace to 3 and then move it to 4, then restart/suspend/add monitor, the window will move back to workspace 3.
could it be that you have a similar scenario like this one?

can you try placing multiple windows on each workspace and tell us whether all windows at workspace#4 move to workspace#3?

**Comment by s3than** [comment] 2019-05-22 00:03
@ebeem I don't have any extensions for moving windows
@mzur I'm running ubuntu 19.04, GNOME Shell 3.32.0 (ubuntu mode)

I'm having a hard time replicating again after that first day. 

I'll continue testing and advise.

**Comment by HadiModarres** [comment] 2019-05-22 00:48
Could it be because of the first install and it gets fixed after a restart?

**Comment by s3than** [comment] 2019-05-22 00:51
@HadiModarres That's possible, I'll keep testing I've got two laptops with the same versions installed so I can try and replicate on them at the same time

**Comment by mzur** [comment] 2019-07-27 09:34
Please reopen if this is still relevant.

**Comment by FOSSforlife** [comment] 2019-07-31 05:39
I'm experiencing this issue. 3x2 grid and I'm running the latest Manjaro with GNOME 3.32.

**Comment by HadiModarres** [comment] 2019-07-31 06:59
I think this is Gnome/Xorg issue, I don't have the plugin installed currently but I see this problem sometimes. It happens every once in a while with a mixture of external screen and suspending. 
Thought this would help you in the right direction. 

Haven't encountered the problem on Wayland so far.

**Comment by mzur** [comment] 2019-07-31 07:21
So this also happens if Workspace Matrix is not installed/disabled? @FOSSforlife Can you confirm this?

**Comment by ebeem** [comment] 2019-07-31 10:18
I made some assumptions and tested `wsmatrix`, it looks like disabling/enabling the extension (which happens on `suspend` and when gnome becomes `idle` for a long time) resets old configuration (without `wsmatrix`) and then overrides it with `wsmatrix`'s configuration.

in case someone has let's say 6 workspaces by default, and 9 with `wsmatrix`, all windows from workspaces 7, 8, and 9 will move to workspace 6, since the default configuration will be restored and `gnome` will have to relocate windows on workspaces that do not exist anymore.

I am not sure whether this should be fixed in `wsmatrix` or not, I think the current behavior makes sense. a workaround to fix this issue is to set workspaces to static and number of workspace to the number u desire.

steps:

1.  go to gnome tweaks, and disable `wsmatrix`
2. from gnome tweaks, go to workspaces, select the option Static Workspaces and set the Number of Workspaces (must be the same number as `wsmatrix`'s workspaces)
3. enable `wsmatrix`


if anyone is facing this issue, please try this solution and let us know if it works.

**Comment by mzur** [comment] 2019-07-31 10:53
Thanks a lot @ebeem! This makes sense and I can reproduce the behavior. One thing we could do is to not [reset the number of workspaces](https://github.com/mzur/gnome-shell-wsmatrix/blob/b79bc0d893eee6c3b1cdecddab1cb2d211ae1d04/wsmatrix%40martin.zurowietz.de/WmOverride.js#L183) if the extension is disabled. This should at least solve the issue if the workspaces were set to "static". I'll have to test what happens in case they were set to "dynamic".

**Comment by ebeem** [comment] 2019-07-31 10:56
I assume dynamic is fine since it will not get rid of the extra workspaces
and yes, I agree with not restoring the number of workspaces as a solution. Changing the number of workspaces in `wsmatrix` should also change gnome's number of workspaces.

**Comment by FOSSforlife** [comment] 2019-07-31 16:09
@ebeem's solution worked for me. When I went to Tweaks -> Workspaces, it said that I had 6 workspaces, which is the amount I should have, but after turning off Workspace Matrix extension it went down to 3. Turning the extension off, changing it, and then turning it back on worked. Thank you all for your help!

**Comment by mzur** [comment] 2019-08-07 16:52
I just published v2.3.0 which resolves this issue if workspaces were set to "static". If they were set to "dynamic", windows will still jump around. I'll leave it at that for now.

**Closed by mzur** 2019-08-07 16:52 UTC
