### ISSUE TITLE
Does not load for me

### ISSUE THREAD

**Issue by thet** [mzur/gnome-shell-wsmatrix#2] opened 2018-10-29 22:43 UTC
I'm using it in a Ubuntu 18.10 / Gnome 3.30.1 environment, but it does not load.
If I knew how, I'd provide more details on the problem...

**Comment by mzur** [comment] 2018-10-30 09:56
Are you Pioxis at `extensions.gnome.org`? You said there is an error after installation. Can you please post more information on the error? I'll try it myself with Ubuntu 18.10 in the next few days.

**Comment by mzur** [comment] 2018-10-30 12:21
Ok, the error is this:
```
[... WmOverride.js 11]: reference to undefined property "screen"
TypeError: global.screen is undefined
```

 I'll have a look.

**Comment by mzur** [comment] 2018-10-30 20:05
I fixed the errors but the following issues remain:

- Users have to set their workspaces to "static" manually (probably is also the case for 3.28)
- The arrow left and right shortcuts do not work
- The arrow up and down shortcuts cycle through the workspaces as if they were still in one dimension on top of each other

**Comment by kamilizmer** [comment] 2018-10-30 23:05
I'm Pioxis.
I can't tell you more than that screen 
<img src="https://i.imgur.com/UxFYHxD.png"/>

**Comment by mzur** [comment] 2018-10-31 07:35
Thanks @kamilizmer. You can display the error logs of GNOME shell with `journalctl /usr/bin/gnome-shell`. I already had a look at this and fixed the errors in the current `master`. I'll make a new release once the issues of my previous post are fixed.

**Comment by mzur** [comment] 2018-11-01 10:41
So apparently there was a bug in Mutter where `workspace.get_neighbor()` did not work for left and right (see [here](https://gitlab.gnome.org/GNOME/mutter/issues/270)). The bug was fixed and merged [a day ago](https://gitlab.gnome.org/GNOME/mutter/merge_requests/245). Maybe the described issues will be fixed by that. I haven't managed to install the latest version of Mutter from source, yet, but I'll try to confirm the fix.

**Comment by mzur** [comment] 2018-11-01 12:58
I couldn't get a custom build of Mutter to work. I'll assume that the abovementioned patch fixes the issue with switching to left and right workspaces. If anyone reading this can confirm that, please do so. @thet @kamilizmer I'll submit a new release with the current changes to extensions.gnome.org. It'll be available after review. You can also download the [latest release](https://github.com/mzur/gnome-shell-wsmatrix/releases) of this repo. But until the issue is solved/the Mutter patch arrives downstream, this extension is of no use in GNOME 3.30, I'm afraid.

**Comment by mzur** [comment] 2018-11-01 15:18
I finally was able to build a patched version of Mutter (based on [these instructions](https://github.com/zakkak/workspace-grid/issues/88#issuecomment-435037672)) and can confirm that the patch resolves the remaining issues described here. You can use the instructions to patch your own Mutter installation or wait for the official release. Closing this as fixed.

**Closed by mzur** 2018-11-01 15:18 UTC
Labels: bug

**Comment by kamilizmer** [comment] 2018-11-04 17:13
> Thanks @kamilizmer. You can display the error logs of GNOME shell with `journalctl /usr/bin/gnome-shell`. I already had a look at this and fixed the errors in the current `master`. I'll make a new release once the issues of my previous post are fixed.

https://pastebin.com/YDAhFAT0

**Comment by mzur** [comment] 2018-11-08 07:37
The fixed version has now been published at extensions.gnome.org.

**Comment by thet** [comment] 2018-11-08 08:05
@mzur thank you! I already tried it and it works very nicely - except for the Bug that only up/down Arrows are working but not left/right. But AFAIK this is related to the Mutter referenced above.

**Comment by thet** [comment] 2018-11-14 19:46
I tried the instructions above to build mutter and it works very nicely. Thanks!
