### ISSUE TITLE
Latest update broken

### ISSUE THREAD

**Issue by yuriw** [mzur/gnome-shell-wsmatrix#118] opened 2020-07-14 18:04 UTC
On Ubuntu 20.04 LTS x86_64 GNOME Shell 3.36.3 the latest update is broken.
After update see red error button and that's all.
Pls fix !

**Comment by ebeem** [comment] 2020-07-14 18:18
I think you just need to restart gnome
press `alt+F2` and then type `r` and hit enter
if you can not do it for some reason, try restarting your machine.

**Comment by yuriw** [comment] 2020-07-14 18:32
@ebeem you are right !
I suspected it but not always can reboot.  Wonder if an extension itself can reload.
This seems like common problem for many extensions

**Comment by mzur** [comment] 2020-07-14 19:16
@yuriw Could you please post the content of `journalctl /usr/bin/gnome-shell` that is relevant to this extension? While a restart fixes the issue, I'd like to know why it happened in the first place.

**Comment by yuriw** [comment] 2020-07-14 19:22
@mzur when i grep for  wsmatrix this is all i see:


                                             _showWorkspaceSwitcher@/home/yuriw/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/WmOverride.js:379:18
                                             _showWorkspaceSwitcher@/home/yuriw/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/WmOverride.js:379:18
                                             _showWorkspaceSwitcher@/home/yuriw/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/WmOverride.js:379:18
                                             _showWorkspaceSwitcher@/home/yuriw/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/WmOverride.js:379:18
                                             _showWorkspaceSwitcher@/home/yuriw/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/WmOverride.js:379:18
                                             _showWorkspaceSwitcher@/home/yuriw/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/WmOverride.js:379:18

**Comment by maxolasersquad** [comment] 2020-07-14 19:56
Same problem here. Same output from journalctl as well.

**Comment by Barben360** [comment] 2020-07-15 06:35
Same problem here, but restarting gnome (alt + F2, r, enter) fixed the problem. Otherwise a restart should work too.

**Comment by matttbe** [comment] 2020-07-15 07:03
Hi

Just for your information, I got this error in `gnome-shell` logs:

```
JS ERROR: Extension wsmatrix@martin.zurowietz.de: Error: A different version was loaded previously. You need to log out for changes to take effect.
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:341:52
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
```

Does that mean the issue is normal in case of update?

Really nice extension BTW! :+1:

**Comment by ebeem** [comment] 2020-07-15 07:12
Thanks for showing this @matttbe 
I am pretty sure this started happening at one version of `GNOME`, it used to show no errors after upgrading.
and suddenly all extensions started to show error after upgrading, so we will need to investigate whether this is actually a `GNOME` problem or the extension's problem.

**Comment by mzur** [comment] 2020-07-15 10:29
[This](https://github.com/mzur/gnome-shell-wsmatrix/compare/v4.0.0...v4.0.1) is the change between v4.0.0 and v4.0.1 of this extension. It doesn't even touch the file `WmOverride.js` as logged by @yuriw.

@ebeem Are you aware of other extensions with similar issues? I'd say that this is a GNOME problem then.

**Comment by tstirrat15** [comment] 2020-07-16 19:11
I'm seeing the same. I wonder what Gnome changed that would cause the issue - I'm not even seeing anything in `journalctl` that looks like an error, but it's still failing to load.

**Comment by arigit** [comment] 2020-07-18 20:03
@tstirrat15 same here. Latest update fails to load; restarting the shell does not help

JS ERROR: Extension wsmatrix@martin.zurowietz.de: Error: A different version was loaded previously>
                                           loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:341:52
                                           callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:39
                                           gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

**Comment by ebeem** [comment] 2020-07-20 13:58
@mzur Sorry for late response, I am pretty sure this was introduced by one `GNOME` versions but I can't recall which one exactly.
We can see this in any extension, I tried it on an officially maintained `GNOME` extension [alternate-tab](https://extensions.gnome.org/extension/15/alternatetab/)

It's very easy to reproduce this error, just downgrade any extension `version` in `metadata.json` and restart `GNOME` (`alt+F2` then type `r`), this will allow you to upgrade the extension from [gnome-extensions](https://extensions.gnome.org)

I got this error
```
Jul 20 16:50:26 ebeem gnome-shell[2137]: JS ERROR: Extension alternate-tab@gnome-shell-extensions.gcampax.github.com: Error: A different version was loaded previously. You need to log out for changes to take effe.
                                         loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:340:52
                                         callback@resource:///org/gnome/shell/ui/extensionDownloader.js:220:39
                                         gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13
```

The fact that `GNOME` handles this error itself means that it's caused by `GNOME`, and apparently it only happens if you previously load another version of the extension (it doesn't occur on fresh install)

**Comment by mzur** [comment] 2020-07-20 17:25
Thanks @ebeem. Then I'll close this as an upstream issue.

**Closed by mzur** 2020-07-20 17:25 UTC
Labels: upstream issue

**Comment by tstirrat15** [comment] 2020-08-13 14:45
I'm confused - is there a current fix for this (short of downgrading Gnome), or is it something where there's a Gnome issue that I should go create/bump?

**Comment by maxolasersquad** [comment] 2020-08-13 14:53
Yes, reboot.

**Comment by mzur** [comment] 2020-08-13 17:47
@tstirrat15 You can go to the [GNOME GitLab](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues) and search for an issue that matches what we observed here or create a new issue if you don't find one. I haven't encountered this issue myself but it seems that a restart of GNOME should fix the issue.

**Comment by tstirrat15** [comment] 2020-08-26 15:23
I was able to fix it by uninstalling the extension (`rm -r` in the `.local/share/gnome-shell/extensions/` folder) and then reinstalling from the gnome extensions site.
