### ISSUE TITLE
Switch-to-workspace left or right on Ubuntu 19.10 Gnome 3.34.2 not working

### ISSUE THREAD

**Issue by borice** [mzur/gnome-shell-wsmatrix#101] opened 2020-03-27 19:48 UTC
Hello. 
I have a brand-new installation of Ubuntu 19.10 with GNOME Tweaks and this extension installed and static workspaces configured as 3x3 matrix.  I would like to be able to navigate this matrix with Ctrl+Alt+Left and Ctrl+Alt+Right (for left- and right- navigation, obviously) in addition to the already-working Ctrl+Alt+Up and Ctrl+Alt+Down.  This doesn't seem to be working.

I tried manually setting this via:
`gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Control><Alt>Left']"` and similarly for Right, but it doesn't seem to work.

Other info:
In overview mode (<Super>W) navigation via Left, Right, Up, Down works fine.
Moving a window from one workspace to another (to the left, right, up, down) also works fine via Ctrl+Shift+Alt+... Left|Right|Up|Down

Any ideas how to get this working?

Thank you so much,
Boris

**Comment by borice** [comment] 2020-03-27 19:54
Hmm... I see others have reported similar issues (#4, #39). I also saw that mutter was supposedly fixed, but can't tell whether the fix was included in the Ubuntu 19.10 release... 

`dpkg -l |grep -i mutter` shows that I have mutter `3.34.3-1ubuntu1~19.10.1`

If this release doesn't contain the fix (which I guess could be since Left/Right navigation isn't working), are there any instructions on how to patch it?  Please, and thank you!

**Comment by mzur** [comment] 2020-03-28 08:30
The bug you are referring to was fixed in Mutter 3.32 so this shouldn't be the issue. You say you have a fresh install, are there no other installed extensions?

**Comment by borice** [comment] 2020-03-28 14:29
nope, no other extensions

**Comment by baldr14** [comment] 2020-03-28 16:22
I can confirm this behaviour on archlinux (gnome-shell 3.36).

**Comment by ebeem** [comment] 2020-03-28 16:29
I am using `arch` with `GNOME Shell 3.36.0`
everything is working well.

Thanks for investigating this @borice 
according to my understanding, the problem seems to be related to the hotkeys binding for some reason.

can you both check the output of 
```
gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-left
gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-right
```

are you getting the expected
```
['<Control><Alt>Left']
['<Control><Alt>Right']
```

**Comment by mzur** [comment] 2020-03-28 16:30
Also: Which version of this extension does each of you use?

**Comment by baldr14** [comment] 2020-03-29 09:19
@ebeem: You are right! Keybindings left/right are ok. Up/down was the problem. 

Here are my korrected setting:

`gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-down`
`['<Super>Page_Down', '<Control><Alt>Down']`

`gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-up`
`['<Super>Page_Up', '<Control><Alt>Up']`

For me all works fine now. @borice: Same problem?

To complete, here are my used extensions:

`gsettings get org.gnome.shell enabled-extensions`

`['dash-to-panel@jderose9.github.com', 'appindicatorsupport@rgcjonas.gmail.com', 'On_Screen_Keyboard_Button@bradan.eu', 'tray-icons@zhangkaizhao.com', 'tweaks-system-menu@extensions.gnome-shell.fifi.org', 'shell-volume-mixer@derhofbauer.at', 'wsmatrix@martin.zurowietz.de']`

**Comment by ebeem** [comment] 2020-06-09 09:50
@borice please feel free to reopen this in case you're still facing issues, as confirmed by baldr14, your problem is related to keybindings, you can check https://github.com/mzur/gnome-shell-wsmatrix/issues/101#issuecomment-605483318 to fix

**Closed by ebeem** 2020-06-09 09:50 UTC
Labels: needs info
