### ISSUE TITLE
Does not work anymore after update

### ISSUE THREAD

**Issue by tmortagne** [mzur/gnome-shell-wsmatrix#52] opened 2019-09-06 07:09 UTC
I just upgraded the extension on https://extensions.gnome.org and it does not work anymore. I can access the configuration but I have the "ERROR" red box and the extension does not seems to be loaded.

Not sure where to get some log to help debug the issue.

**Comment by tmortagne** [comment] 2019-09-06 07:13
Note: a restart of the computer actually fixed it. Not sure if it's the expected behavior or if the issue should be kept for the "just after upgrade" use case.

**Comment by Koldar** [comment] 2019-09-06 07:15
Just happened to me at the upgrade. No, I don't think this should be the expected behaviour since it throw an error without message to the user. IMHO should be regarded as a bug :)

**Comment by mzur** [comment] 2019-09-06 07:25
This issue is caused because the settings schema of this extension was renamed. Apparently GNOME can't handle this case when an extension is updated. I suggested to remove the extension, restart GNOME and then reinstall the extension. But I suspect that a restart of GNOME would be enough, too. Can anyone confirm that?

This isn't really a bug of this extension since no code or file is actually broken. This could have been prevented if the schema name would have been kept but I didn't know that this would be an issue. I thought about changing it back but this would break the update again for everyone who already updated the extension.

**Comment by tmortagne** [comment] 2019-09-06 08:19
> I thought about changing it back but this would break the update again for everyone who already updated the extension.

Well we know the trick now so maybe better be nice to the poor souls who did not hit this yet ? :)

**Comment by Koldar** [comment] 2019-09-06 09:42
totally agree, now they have the right solution.

**Comment by mzur** [comment] 2019-09-06 10:52
I'm not 100% sure if reverting the name fixes the issue since it was done for a reason. The extension added a new schema for keybindings and I suspect that this would be the next cause for the same error. I think I rather leave the change as it is. If people care about the extension they will quickly notice how to fix the issue. If restarting GNOME is the only thing that's required (as it looks like), it's a simple fix.

**Comment by lasseebert** [comment] 2019-09-06 18:35
Can confirm that a restart (of the entire host) helped for me :+1: My guess is that people will either come here and see tips to get it working, or will eventually restart.

**Comment by packoman** [comment] 2019-09-07 18:59
So I was also bitten by this and eventually ended up here. So ok. Could the necessity for a restart be indicated here(?): https://extensions.gnome.org/extension/1485/workspace-matrix/
I suspect, that the not-so-savvy might not got directly to the Github issues (at least I did not think of it immediately).

**Comment by mzur** [comment] 2019-09-07 19:32
It's in the second comment right now. But I've also added a note to the description. That should be more visible.

**Comment by packoman** [comment] 2019-09-08 18:40
Oh. I guess, I should have read the comments. Sorry.
Anyway: Great plugin, really saved the workflow/environment-layout that I have grown accustomed to from Unity and transition to gnome-shell.

**Comment by packoman** [comment] 2019-09-08 18:45
Oh. This just came to mind: Is there a way to request features? Because I would really love to see the following:

A configurable timeout for when the workspace-layout mini-view-overlay disappears (not sure if I am making my self clear). In Unity this only disappeared, once you let go of Ctrl+Alt after hitting an arrow button+Ctrl+Alt.

This gave me time to orientate myself and find the workspace that I want to go to in case I do not know out of my head.

**Comment by ebeem** [comment] 2019-09-08 18:52
@packoman there is already a configurable timeout for the workspace layout in extension preferences, but it does not keep the layout shown while `ctrl+alt` combination is pressed.

and yes, you can request a new feature by creating an issue in this github repository.

**Comment by mzur** [comment] 2019-09-09 06:51
@packoman To add to @ebeem's answer: Most features are implemented for GNOME 3.32. If you use an oder version of GNOME, you get only the basic features.

**Comment by PabloKowalczyk** [comment] 2019-09-17 11:08
My solution to update (tested on Ubuntu 19.04):

- delete all files from `~/.local/share/gnome-shell/extensions`
- copy new files to `~/.local/share/gnome-shell/extensions`
- press `Alt + F2`, type `r` and hit `enter`
- after some seconds GNOME is reloaded with new version of plugin :tada: 

Hope it helps someone :)

**Comment by mzur** [comment] 2019-09-17 11:11
@PabloKowalczyk It should be enough to reload GNOME with <kbd>Alt</kbd>+<kbd>F2</kbd> and `r`.

**Comment by mzur** [comment] 2019-10-08 15:28
I'll close this as this issue should be resolved for most users by now.

**Closed by mzur** 2019-10-08 15:28 UTC
